version: "3"
services:
  db:
    image: "postgres"
    container_name: "postgres-container"
    environment:
      - POSTGRES_USER=efeeney
      - POSTGRES_PASSWORD=koch2912
      - POSTGRES_DB=books
    ports:
      - "5432:5432"
    volumes:
      - '/tmp/postgres-container:/var/lib/postgresql/data'
